### ISSUE TITLE
Window content not rendered at launch.

### ISSUE THREAD

**Issue by vanwalj** [radjivC/whatsapp-desktop#1]
Sorry, i can't test the client since the iOS client don't allow yet to scan the qrcode to allow the desktop app.

But i think this may solve the problem:

window.dispatchEvent(new Event('resize'));

Just put this a the onload event.

This is a bit hacky, but this should work :)

**Comment by radjivF** [comment]
I tried but still doesn't work :(

**Comment by radjivF** [comment]
Indeed I think I need a redraw, but still nothing happens

**Comment by radjivF** [comment]
I fixed it :)

**Comment by vanwalj** [comment]
Nice !
How did you do that ? :)

**Comment by radjivF** [comment]
The problem was from the whatapps React interface, the nodewebkit windows couldn't see the modifcation of the DOM so it can't redraw the windows.
I change the the webview to a frame object and call this functions

```
  //this events are here to repaint the frame :bug from react version used by whatsapp.web
  win.on('closed', function(view) {
    console.log('closed');
  });
  win.on('loaded', function(view) {
    console.log('loaded');
  });
  win.on('  document-end', function(view) {
    console.log('document-end');
  });
  win.on('loading', function(view){
    console.log('loading');
  });
  win.on('document-start', function(view){
    console.log('document-start');
  })
```

with nothing inside but like that every Dom event nodewebkit repaint the windows.

I found it by chance hahah
